### ISSUE TITLE
Bug in alias for enum.(posible solution added)

### ISSUE THREAD

**Issue by joolfe** [icebob/fastest-validator#130]
Hi,

I have found a little bug using alias, to reproduce just:

```
const v = new Validator();

v.alias('algList', { type: "array", items: "string", enum: ['RS256' , 'PS256'] });

const toValidate = {
    request_object_signing_alg_values_supported: ['RS256S']
}

const schema = { 
     request_object_signing_alg_values_supported: "algList"
};

const check = v.compile(schema);

console.log("First:", check(toValidate));
```

Im getting the error

```
/node_modules/fastest-validator/lib/rules/array.js:70
                                        ${this.makeError({ type: "arrayEnum", expected: "\"" + schema.enum.join(", ") + "\"", actual: "value[i]", messages })}
                                                                                                           ^
TypeError: schema.enum.join is not a function
```

After debug a bit i have seen that `schema` has the value 

```
{
  type: 'array',
  items: 'string',
  enum: { '0': 'RS256', '1': 'PS256' }
}
```

The enum field has been modified for an Object, the problem is in `/fastest-validator/lib/helpers/deep-extend.js` file because is checking object just with `typeof source[property] === "object"` and this is also true for an array.

As possible solution i purpose to replace thia check with a `source[property].constructor !== Object` or add an additional check in the same if like `!Array.isArray(source[property]) &&`

Best Regards.

**Comment by icebob** [comment]
I think it has been fixed in https://github.com/icebob/fastest-validator/pull/128 but it's not released yet.
Could you check the latest code with `npm i icebob/fastest-validator`?

**Comment by joolfe** [comment]
Hi!,

I have tested and is still failing, i have put a log in the `deepExtend`  function and show

```
isObjectHasKeys(enum) => true
```

Thats basically because the code `Object.keys(v).length > 0;` return true for arrays as:

```
var test = ['hello']

Object.keys(test)
// [ '0' ]
```

I think if this method need to detect Objects only the solution should be `source[property].constructor !== Object` as is the most trustworthy way that i know.

Best Regards.

**Comment by icebob** [comment]
Yes, it was the first version what @erfanium did in #128 but I said it can cause problem if the object is created as `Object.create(null)`. In this case, it has no constructor.

Any idea @joolfe @erfanium

**Comment by joolfe** [comment]
In this case i think the easiest solution is to add a `!Array.isArray(source[property])` to ensure is not an array....

**Comment by icebob** [comment]
@joolfe erfanium fixed in #131. Could you try it again? If it works, I will release a new version

**Comment by joolfe** [comment]
Tested and working perfectly, Thanks!

**Comment by icebob** [comment]
Thanks. I've just released in 1.3.0
